"""src/SkillNamesEn.inc: English names by skill and buff id, for logs from clients in other languages (src/Evtc.cpp).

ArcDPS writes the names in the client's language ("Relique du heraut"); the analysis finds some buffs by English name and
the UI is English. Names come from English logs (the skill table of every log whose language event says English: buffs
and effects too, which the GW2 API doesn't list) and from the API tables already generated (src/SkillText.inc,
src/SkillSlots.inc); for an id named both ways, the logs' name wins (it's what an English client shows).

    python tools/gen_skill_names.py [log folder ...]      default: the ArcDPS log folder in Documents
Standard library only.
"""
import collections
import os
import re
import struct
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from evtc import AGENT, EVENT, SC, SRC, STATECHANGE  # noqa: E402

ROOT = os.path.normpath(os.path.join(HERE, ".."))
DEFAULT = os.path.join(os.path.expanduser("~"), "Documents", "Guild Wars 2", "addons", "arcdps", "arcdps.cbtlogs")


def log_names(path):
    """the skill table of an English log, else None"""
    with zipfile.ZipFile(path) as z:
        data = z.read(z.namelist()[0])
    if data[:4] != b"EVTC":
        return None
    pos = 16
    (n,) = struct.unpack_from("<I", data, pos)
    pos += 4 + n * AGENT.size
    (m,) = struct.unpack_from("<I", data, pos)
    pos += 4
    names = {}
    for i in range(m):
        sid, raw = struct.unpack_from("<i64s", data, pos + i * 68)
        names[sid] = raw.split(b"\0")[0].decode("utf-8", "replace")
    pos += m * 68
    end = min(len(data), pos + 5000 * EVENT.size)
    for e in EVENT.iter_unpack(data[pos:pos + (end - pos) // EVENT.size * EVENT.size]):
        if e[STATECHANGE] == SC["LANGUAGE"]:
            return names if e[SRC] == 0 else None
    return None


def api_names():
    out = {}
    for inc, pat in (("SkillText.inc", r'\{(-?\d+), "((?:[^"\\]|\\.)*)"'), ("SkillSlots.inc", r'\{(-?\d+), \d+, -?\d+, "((?:[^"\\]|\\.)*)"')):
        with open(os.path.join(ROOT, "src", inc), encoding="utf-8") as f:
            for m in re.finditer(pat, f.read()):
                out[int(m.group(1))] = m.group(2).encode().decode("unicode_escape") if "\\" in m.group(2) else m.group(2)
    return out


def main(folders):
    seen = collections.defaultdict(collections.Counter)
    logs = english = 0
    for folder in folders:
        for d, _, files in os.walk(folder):
            for name in files:
                if not name.endswith(".zevtc"):
                    continue
                logs += 1
                try:
                    names = log_names(os.path.join(d, name))
                except (zipfile.BadZipFile, struct.error, OSError):
                    continue
                if names is None:
                    continue
                english += 1
                for sid, n in names.items():
                    if n and not n.isdigit():
                        seen[sid][n] += 1
    table = {sid: c.most_common(1)[0][0] for sid, c in seen.items()}
    api = api_names()
    for sid, n in api.items():
        table.setdefault(sid, n)
    esc = lambda s: s.replace("\\", "\\\\").replace('"', '\\"')
    out = os.path.join(ROOT, "src", "SkillNamesEn.inc")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/gen_skill_names.py from English logs and the GW2 API tables: English names by skill and buff id,\n")
        f.write("// for logs from clients in other languages (src/Evtc.cpp). Sorted by id. Do not edit.\n")
        f.write("struct SkillNameEn { int32_t Skill; const char* Name; };\n")
        f.write("const SkillNameEn kSkillNamesEn[] = {\n")
        for sid in sorted(table):
            f.write(f'\t{{{sid}, "{esc(table[sid])}"}},\n')
        f.write("};\n")
    print(f"{english} English logs of {logs}; {len(seen)} ids from logs, {len(api)} from the API tables, {len(table)} in all -> {os.path.relpath(out, ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1:] or [DEFAULT])
