"""Which skills remove conditions (cleanse) or boons (strip), and which boons each skill gives, from the public GW2
API's skill facts.

The log says a condition or boon was removed (or a boon applied) and by whom, not by which skill. src/Analysis.cpp
only credits a cleanse, strip or boon to a skill that these lists say does it; everything else goes to "other
sources" (traits, relics, sigils, runes, combo fields).

Writes src/RemovalSkills.inc, src/BoonSkills.inc, src/UseBuffs.inc and data/removal_skills.txt (a readable list).

Usage:
    python tools/gen_removal_skills.py
"""
import json
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "FightReview/0.1"})
    return json.loads(urllib.request.urlopen(req, timeout=60).read())


def removes(skill):
    """(cleanses, strips) from the skill's facts and traited facts"""
    texts = []
    for f in skill.get("facts", []) + skill.get("traited_facts", []):
        texts.append(f"{f.get('text', '')} {f.get('type', '')}".lower())
    cleanse = any("condition" in t and ("remov" in t or "cleans" in t or "cure" in t) for t in texts)
    strip = any("boon" in t and ("remov" in t or "strip" in t or "corrupt" in t) for t in texts)
    desc = skill.get("description", "").lower()
    cleanse |= "remove" in desc and "condition" in desc or "cure" in desc and "condition" in desc
    strip |= ("remove" in desc or "strip" in desc) and "boon" in desc
    return cleanse, strip


# Analysis::kBoonNames order (TopStats')
BOONS = ["Might", "Fury", "Quickness", "Alacrity", "Protection", "Regeneration", "Vigor", "Aegis", "Stability",
         "Swiftness", "Resistance", "Resolution"]


def gives(skill):
    """Bit mask of the boons in the skill's facts (Buff / PrefixedBuff with a boon status), traited facts included"""
    mask = 0
    for f in skill.get("facts", []) + skill.get("traited_facts", []):
        if f.get("type") in ("Buff", "PrefixedBuff") and f.get("status") in BOONS:
            mask |= 1 << BOONS.index(f["status"])
    return mask


def main():
    skills, page = [], 0
    while True:
        try:
            batch = get(f"https://api.guildwars2.com/v2/skills?page={page}&page_size=200")
        except urllib.error.HTTPError:
            break
        if not batch:
            break
        skills += batch
        page += 1
    cleanse, strip = {}, {}
    for s in skills:
        c, st = removes(s)
        if c:
            cleanse[s["id"]] = s.get("name", "")
        if st:
            strip[s["id"]] = s.get("name", "")
    boons = {s["id"]: (gives(s), s.get("name", "")) for s in skills if gives(s)}
    with open(os.path.join(ROOT, "src", "BoonSkills.inc"), "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_removal_skills.py from the GW2 API's skill facts. Do not edit.\n")
        f.write("// {skill id, bit mask of the boons it gives, in Analysis::kBoonNames order}\n")
        f.write("const std::pair<int32_t, uint32_t> kBoonSkills[] = {" +
                ", ".join(f"{{{i}, {m}}}" for i, (m, n) in sorted(boons.items())) + "};\n")
    # Names that mark a use in the log without a cast event: a profession mechanic (F1-F5, any spec of the class)
    # puts a buff of its own name on the player while it's on (tomes, shrouds, attunements, legendary stances,
    # Berserk, chants); a signet's passive buff is removed when it's used. Plus mode buffs the API names differently.
    profession = sorted({s["name"] for s in skills if str(s.get("slot", "")).startswith("Profession") and s.get("name")})
    profession += ["Lute Playing", "Flute Playing", "Harp Playing", "Drum Playing", "Radiant Shroud"]
    signets = sorted({s["name"] for s in skills if s.get("name", "").startswith("Signet of")})
    quote = lambda n: '"' + n.replace("\\", "\\\\").replace('"', '\\"') + '"'
    with open(os.path.join(ROOT, "src", "UseBuffs.inc"), "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_removal_skills.py from the GW2 API's skill list. Do not edit.\n")
        f.write("const char* const kProfessionSkillNames[] = {" + ", ".join(quote(n) for n in profession) + "};\n")
        f.write("const char* const kSignetNames[] = {" + ", ".join(quote(n) for n in signets) + "};\n")
    lines = ["// Generated by tools/gen_removal_skills.py from the GW2 API's skill facts. Do not edit.",
             "const int32_t kCleanseSkills[] = {" + ", ".join(str(i) for i in sorted(cleanse)) + "};",
             "const int32_t kStripSkills[] = {" + ", ".join(str(i) for i in sorted(strip)) + "};"]
    with open(os.path.join(ROOT, "src", "RemovalSkills.inc"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
    with open(os.path.join(ROOT, "data", "removal_skills.txt"), "w", encoding="utf-8") as f:
        for title, table in (("cleanse", cleanse), ("strip", strip)):
            for i, n in sorted(table.items(), key=lambda kv: kv[1]):
                f.write(f"{title}\t{i}\t{n}\n")
        for i, (m, n) in sorted(boons.items(), key=lambda kv: kv[1][1]):
            f.write(f"boons\t{i}\t{n}\t{', '.join(b for k, b in enumerate(BOONS) if m >> k & 1)}\n")
    print(f"{len(skills)} skills: {len(cleanse)} cleanse, {len(strip)} strip, {len(boons)} give boons")


if __name__ == "__main__":
    main()
