"""Which slot each profession skill sits in (heal, utility, elite), from the public GW2 API.

The log doesn't say which utility skills a player slotted. Post-fight we infer it from what they cast: a Mesmer who
cast three different utility skills and not Illusion of Life that round didn't carry it (the user, 2026-09-24).
Skills that share a slot (a mantra and the power skill it turns into, any flip skill) get the same root id, so they
count as one slot.

Writes src/SkillSlots.inc.

Usage:
    python tools/gen_skill_slots.py
"""
import json
import re
import os
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
SLOTS = {"Heal": 1, "Utility": 2, "Elite": 3}


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "FightReview/0.1"})
    return json.loads(urllib.request.urlopen(req, timeout=60).read())


def main():
    skills, page = [], 0
    while True:
        try:
            batch = get(f"https://api.guildwars2.com/v2/skills?page={page}&page_size=200")
        except urllib.error.HTTPError:
            break
        if not batch:
            break
        skills += batch
        page += 1
    slotted = {s["id"]: s for s in skills if s.get("slot") in SLOTS and s.get("professions")}

    # Root: the smallest id among skills linked by flip_skill (both ways), within slotted skills
    parent = {i: i for i in slotted}

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for s in slotted.values():
        other = s.get("flip_skill")
        if other in slotted:
            a, b = find(s["id"]), find(other)
            parent[max(a, b)] = min(a, b)

    with open(os.path.join(ROOT, "src", "SkillSlots.inc"), "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/gen_skill_slots.py from the GW2 API: skill id, slot (1 heal, 2 utility, 3 elite), root id\n")
        fh.write("// (skills sharing a slot, like a mantra and its power skill, share the root), name (logs use other ids for some).\n")
        fh.write("// Do not edit.\n")
        fh.write("struct SkillSlot { int32_t Skill; uint8_t Slot; int32_t Root; const char* Name; };\n")
        fh.write("const SkillSlot kSkillSlots[] = {\n")
        for i in sorted(slotted):
            fh.write(f"\t{{{i}, {SLOTS[slotted[i]['slot']]}, {find(i)}, {json.dumps(slotted[i]['name'], ensure_ascii=False)}}},\n")
        fh.write("};\n")
    print(f"{len(skills)} skills, {len(slotted)} in a heal, utility or elite slot; wrote src/SkillSlots.inc")

    # What each skill does, for tooltips (the API's description, markup removed, at most 200 characters)
    described = {}
    for s in skills:
        text = re.sub(r"<[^>]+>", "", s.get("description", "")).replace("\n", " ").strip()
        if text:
            described[s["id"]] = (s["name"], text[:200])
    with open(os.path.join(ROOT, "src", "SkillText.inc"), "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/gen_skill_slots.py from the GW2 API: skill id, name, description (for tooltips). Do not edit.\n")
        fh.write("struct SkillText { int32_t Skill; const char* Name; const char* Text; };\n")
        fh.write("const SkillText kSkillTexts[] = {\n")
        for i in sorted(described):
            name, text = described[i]
            fh.write(f"\t{{{i}, {json.dumps(name, ensure_ascii=False)}, {json.dumps(text, ensure_ascii=False)}}},\n")
        fh.write("};\n")
    print(f"{len(described)} skills with a description; wrote src/SkillText.inc")


if __name__ == "__main__":
    main()
