#pragma once
// Instant casts: skills without an animation, found from what they leave in the log with Elite Insights'
// rules (src/CastRules.inc, generated by tools/gen_cast_rules.py). Port of tools/instant_casts.py.

#include <cstdint>
#include <unordered_map>
#include <utility>
#include <vector>

#include "Evtc.h"

namespace InstantCasts
{
	// caster (player agent) -> [(log time, skill id)]
	std::unordered_map<uint64_t, std::vector<std::pair<int64_t, int32_t>>> Find(const Evtc::Log& aLog);

	// Elite Insights' display name for a skill, if it has one; aFallback: its constant name, use last.
	const char* Name(int32_t aSkill, bool aFallback);
}
